apiVersion: apps/v1
kind: Deployment
metadata:
  name: HomeAssistant
  labels:
    app: HomeAssistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HomeAssistant
  template:
    metadata:
      labels:
        app: HomeAssistant
    spec:
      containers:
        - name: HomeAssistant
          image: fra.ocir.io/<DOCKER_OBJECT_STORAGE_NAMESPACE>/free-kubernetes-nginx:latest
          ports:
            - containerPort: 8123
      imagePullSecrets:
      - name: free-registry-secret